# Templateから拾ってきているだけなので、疎通通すために
# 修正が必要
version: "3.9"
services:
  backend:
    build:
      context: ./backend
    env_file:
      - .example.envrc
    ports:
      - "8080:5000"
    depends_on:
      - db
  db:
    image: postgres:15-bullseye
    env_file:
      - .example.envrc
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql