name: Golang lint and format

on:
  pull_request:
    branches: ["main"]
    paths: ['backend/**']

concurrency:
  group: "golang"
  cancel-in-progress: false

jobs:
  # lint and format
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Backend
        uses: actions/setup-go@v4
        with:
          # 1.21.2 で固定している
          go-version: '1.21.2'
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false

